INSERT INTO FACULTIES(DESCRIPTION) VALUES ('Medicinca Humana');
INSERT INTO FACULTIES(DESCRIPTION) VALUES ('Odontología');
INSERT INTO FACULTIES(DESCRIPTION) VALUES ('Ciencias Contables');
INSERT INTO FACULTIES(DESCRIPTION) VALUES ('Ingeniería Electrónica y Eléctrica');
INSERT INTO FACULTIES(DESCRIPTION) VALUES ('Ingeniería Sistemas e Informática');

SELECT * FROM FACULTIES;

INSERT INTO SCHOOLS(NAME, NUMBEROFSTUDENTS, TAXRESOURCE, LICENCED, CLASIFICATION, FACULTIESID) VALUES ('Enfermería', 0, 0, 1, 1, 1);
INSERT INTO SCHOOLS(NAME, NUMBEROFSTUDENTS, TAXRESOURCE, LICENCED, CLASIFICATION, FACULTIESID) VALUES ('Odontología', 0, 0, 1, 1, 2);
INSERT INTO SCHOOLS(NAME, NUMBEROFSTUDENTS, TAXRESOURCE, LICENCED, CLASIFICATION, FACULTIESID) VALUES ('Gestión Tributaria', 0, 0, 1, 1, 3);
INSERT INTO SCHOOLS(NAME, NUMBEROFSTUDENTS, TAXRESOURCE, LICENCED, CLASIFICATION, FACULTIESID) VALUES ('Ingeniería Electrónica', 0, 0, 1, 1, 4);
INSERT INTO SCHOOLS(NAME, NUMBEROFSTUDENTS, TAXRESOURCE, LICENCED, CLASIFICATION, FACULTIESID) VALUES ('Ingeniería Biomédica', 0, 0, 1, 1, 4);
INSERT INTO SCHOOLS(NAME, NUMBEROFSTUDENTS, TAXRESOURCE, LICENCED, CLASIFICATION, FACULTIESID) VALUES ('Ingeniería de Sistemas', 0, 0, 1, 1, 5);
INSERT INTO SCHOOLS(NAME, NUMBEROFSTUDENTS, TAXRESOURCE, LICENCED, CLASIFICATION, FACULTIESID) VALUES ('Ingeniería de Software', 0, 0, 1, 1, 5);

SELECT * FROM SCHOOLS;