-- FACULTIES
CREATE SEQUENCE FACULTIES_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FACULTIES_TRG
BEFORE INSERT ON FACULTIES
FOR EACH ROW
BEGIN
  SELECT FACULTIES_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;

-- SCHOOLS
CREATE SEQUENCE SCHOOLS_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SCHOOLS_TRG
BEFORE INSERT ON SCHOOLS
FOR EACH ROW
BEGIN
  SELECT SCHOOLS_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;